# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-mazelock-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    MazeLock patch for Devicelock
Version:    0.0.11
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   sailfish-version >= 1.1.1
Requires:   lipstick-jolla-home-qt5 >= 0.23.20.9

%description
MazeLock patch for Devicelock


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-mazelock-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-mazelock-patch
mkdir -p %{buildroot}/usr/share/jolla-settings/pages/sailfishos-mazelock-patch
cp -r settings/*.qml %{buildroot}/usr/share/jolla-settings/pages/sailfishos-mazelock-patch
mkdir -p %{buildroot}/usr/share/jolla-settings/entries
cp -r settings/*.json %{buildroot}/usr/share/jolla-settings/entries/
# << install pre

# >> install post
# << install post

%pre
# >> pre
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-mazelock-patch || true
fi
# << pre

%preun
# >> preun
if [ -f /usr/sbin/patchmanager ]; then
/usr/sbin/patchmanager -u sailfishos-mazelock-patch || true
fi
# << preun

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-mazelock-patch
%{_datadir}/jolla-settings/entries
%{_datadir}/jolla-settings/pages
# >> files
# << files
