# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-mazelock-patch

# >> macros
BuildArch: noarch
# << macros

Summary:    MazeLock patch for Devicelock
Version:    0.0.3
Release:    1
Group:      Qt/Qt
License:    TODO
Source0:    %{name}-%{version}.tar.bz2
Requires:   patchmanager
Requires:   sailfish-version >= 1.1.1
Requires:   lipstick-jolla-home-qt5 >= 0.23.20.9

%description
MazeLock patch for Devicelock


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/usr/share/patchmanager/patches/sailfishos-mazelock-patch
cp -r patch/* %{buildroot}/usr/share/patchmanager/patches/sailfishos-mazelock-patch
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager/patches/sailfishos-mazelock-patch
# >> files
# << files
